/*
 * iam
 *
 * iam api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateUserRequest struct {

	Username string `json:"username"`

	Password string `json:"password"`

	Email string `json:"email"`
}
