/*
 * iam
 *
 * iam api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Permission struct {

	ServiceName string `json:"serviceName"`

	ResourceType string `json:"resourceType"`

	ResourceId string `json:"resourceId"`

	Action []string `json:"action"`

	Effect string `json:"effect"`
}
