/*
 * iam
 *
 * iam api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnforcePermissionReq struct {

	ServiceName string `json:"serviceName"`

	ResourceType string `json:"resourceType"`

	ResourceId string `json:"resourceId,omitempty"`

	Action string `json:"action"`
}
