/*
 * iam
 *
 * iam api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ValidateOperation200Response struct {

	Result bool `json:"result,omitempty"`
}
