/*
 * iam
 *
 * iam api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Login200Response struct {

	// The token to be used for subsequent authenticated requests.
	Token string `json:"token,omitempty"`
}
