/*
 * iam
 *
 * iam api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Signup201Response struct {

	Id string `json:"id,omitempty"`

	Username string `json:"username,omitempty"`
}
