/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Label struct {

	// the id of the label
	Id string `json:"id,omitempty"`

	// the name of the label
	Name string `json:"name"`

	// the super category name
	SuperCategoryName string `json:"superCategoryName,omitempty"`

	Color int32 `json:"color"`

	// the defination of the key points
	KeyPointDef []string `json:"keyPointDef,omitempty"`

	KeyPointSkeleton [][]int32 `json:"keyPointSkeleton,omitempty"`

	CoverImageUrl string `json:"coverImageUrl,omitempty"`
}
