/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataPoolDetails struct {

	// The data pool name
	Name string `json:"name,omitempty"`

	// The data pool description
	Description string `json:"description,omitempty"`

	// The data pool created time
	CreatedAt int64 `json:"createdAt,omitempty"`

	// The data pool updated time
	UpdatedAt int64 `json:"updatedAt,omitempty"`
}
