/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataPoolStatistics struct {
	RawDataCount int32 `json:"rawDataCount,omitempty"`

	// the number of labels in the annotation data view.
	LabelCount int32 `json:"labelCount,omitempty"`

	// the distribution of labels in the annotation data view.
	LabelDistribution []LabelDistribution `json:"labelDistribution,omitempty"`

	// the total size of the data in the data view in bytes.
	TotalDataSize int64 `json:"totalDataSize,omitempty"`
}
