/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AnnotationTemplateDetails struct {

	// the id of the annotation template
	Id string `json:"id,omitempty"`

	// name of the annotation template
	Name string `json:"name,omitempty"`

	// Unix timestamp in ms
	CreateAt int64 `json:"createAt,omitempty"`

	// Unix timestamp in ms
	UpdateAt int64 `json:"updateAt,omitempty"`

	// the type of the annotation template
	Type string `json:"type,omitempty"`

	Labels []Label `json:"labels,omitempty"`

	WordList []string `json:"wordList,omitempty"`
}
