/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataItemListDataListInner struct {

	// The dataset raw data id
	RawDataId string `json:"rawDataId,omitempty"`

	// The dataset annotation id
	AnnotationId string `json:"annotationId,omitempty"`

	// The dataset raw data url
	RawDataUrl string `json:"rawDataUrl,omitempty"`

	// The dataset annotation url
	AnnotationUrl string `json:"annotationUrl,omitempty"`

	LabelList []string `json:"labelList,omitempty"`
}
