/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataItemList struct {

	// The dataset raw data type
	RawDataType string `json:"rawDataType,omitempty"`

	// The dataset annotation template id
	AnnotationTemplateId string `json:"annotationTemplateId,omitempty"`

	// The dataset annotation template type
	AnnotationTemplateType string `json:"annotationTemplateType,omitempty"`

	DataList []DataItemListDataListInner `json:"dataList,omitempty"`
}
