/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateAnnotationTemplateRequest struct {

	// name of the annotation template
	Name string `json:"name"`

	// the type of the annotation template
	Type string `json:"type"`

	// the description of the annotation template
	Description string `json:"description,omitempty"`

	Labels []Label `json:"labels,omitempty"`

	WordList []string `json:"wordList,omitempty"`

	// whether create the annotation template from existed annotation template
	IsCreateFromExisted bool `json:"isCreateFromExisted,omitempty"`

	// the id of the existed annotation template
	ExistedAnnotationTemplateId string `json:"existedAnnotationTemplateId,omitempty"`
}
