/*
 * optimus
 *
 * optimus api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DataPartition - The data partition ratio. The sum of train, test and validation must be 100.
type DataPartition struct {
	Train int32 `json:"train"`

	Test int32 `json:"test"`

	Validation int32 `json:"validation"`
}
