/*
 * iam
 *
 * iam api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	router.MaxMultipartMemory = 32 << 20 // 32 MiB
	router.Use(ErrorHandler())
	router.Use(PanicHandler())
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/api/open/v1/",
		Index,
	},

	{
		"Login",
		http.MethodPost,
		"/api/open/v1/login",
		Login,
	},

	{
		"Signup",
		http.MethodPost,
		"/api/open/v1/signup",
		Signup,
	},

	{
		"CreatePermission",
		http.MethodPost,
		"/api/open/v1/permissions",
		CreatePermission,
	},

	{
		"DeletePermission",
		http.MethodDelete,
		"/api/open/v1/permissions",
		DeletePermission,
	},

	{
		"ValidateOperation",
		http.MethodPost,
		"/api/open/v1/validate-operation",
		ValidateOperation,
	},

	{
		"GetTokenInfo",
		http.MethodGet,
		"/api/open/v1/token-info",
		GetTokenInfo,
	},
}
